include $(CLEAR_VARS)

LOCAL_MODULE := AsusCamera
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := AsusCamera/AsusCamera.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Camera2
LOCAL_PRIVILEGED_MODULE := true

include $(BUILD_PREBUILT)